server:
  port: 7031

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

 eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.2:7001/eureka/,http://172.17.0.3:7002/eureka/
