eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdemo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: bmisAdmin
    password: qkxs@1234