server:
  port: 5000

spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      default-filters:
        - Elapsed=true
      routes:
      - id: user
        uri: lb://USER-SERVICE
        order: 0
        predicates:
          - Path=/user/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - id: blog
        uri: lb://BLOG-SERVICE
        order: 0
        predicates:
          - Path=/blog/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

#Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 0 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 5 # 连接池中的最小空闲连接
      timeout: 0  # 连接超时时间（毫秒）
           # -------
#           - name: RequestRateLimiter
#             args:
#               key-resolver: "#{@remoteAddrKeyResolver}"
#               redis-rate-limiter:
#                replenishRate: 1
#                burstCapacity: 5
#               status: 401
           # -------
  # -------
  sleuth:
    web:
      client:
        enabled: true #打开sleuth客户端功能
    sampler:
      probability: 1.0 #将采样比设置为1，全部采样，默认为0.1
    zipkin:
      base-url: http://localhost:9411/ #指定链路追踪服务地址

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
  # -------
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.springcloud.cloudgateway.filter: debug

status: 302
url: http://10.2.72.111:5000/user/web/login
