server:
  port: 5000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      default-filters:
#        - Elapsed=true
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@remoteAddrKeyResolver}"
#            redis-rate-limiter:
#              replenishRate: 1
#              burstCapacity: 5
#            status: 401
      routes:
       - id: test
         uri: lb://TEST-SERVICE
         order: 0
         predicates:
           - Path=/test/**
         filters:
           - StripPrefix=1
           - AddResponseHeader=X-Response-Default-Foo, Default-Bar
       - id: user
         uri: lb://USER-SERVICE
         order: 0
         predicates:
          - Path=/user/**
         filters:
           - StripPrefix=1
           - AddResponseHeader=X-Response-Default-Foo, Default-Bar
           # -------
#           - name: RequestRateLimiter
#             args:
#               key-resolver: "#{@remoteAddrKeyResolver}"
#               redis-rate-limiter:
#                replenishRate: 1
#                burstCapacity: 5
#               status: 401
           # -------
  # -------

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
  # -------
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.springcloud.cloudgateway.filter: debug