server:
  port: 9999

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.qk.uaaserver.entity                  # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml


