server:
  port: 8751

spring:
  zipkin:
    base-url: http://localhost:9411

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.qk.userservice.entity                  # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

#  rabbitmq:
#    host: 10.2.72.108
#    port: 5672
#    username: admin
#    password: admin
#    publisher-confirms: true
#    virtual-host: /


feign:
  hystrix:
    enabled: true